/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appswing;

import javax.swing.JOptionPane;

/**
 *
 * @author Red5
 */
public class jfAppSwingII extends javax.swing.JFrame {

    /**
     * Creates new form jfAppSwingII
     */
    public jfAppSwingII() {
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jlMensaje = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAcciones = new javax.swing.JMenu();
        jmiSaludar = new javax.swing.JMenuItem();
        jmiInicializar = new javax.swing.JMenuItem();
        jmAyuda = new javax.swing.JMenu();
        jmiAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Saludar");
        jButton1.setToolTipText("Este boton saludará");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saludarActionPerformed(evt);
            }
        });

        jlMensaje.setText("Hola esta aplicación saludará utilizando Swing");
        jlMensaje.setToolTipText("jlMensaje");

        jtfNombre.setText("Nombre");
        jtfNombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                guardaTexto(evt);
            }
        });
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jmAcciones.setText("Acciones");

        jmiSaludar.setText("Saludar");
        jmiSaludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saludarActionPerformed(evt);
            }
        });
        jmAcciones.add(jmiSaludar);

        jmiInicializar.setText("Inicializar");
        jmiInicializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInicializarActionPerformed(evt);
            }
        });
        jmAcciones.add(jmiInicializar);

        jMenuBar1.add(jmAcciones);

        jmAyuda.setText("Ayuda");

        jmiAcercade.setText("Acerca de");
        jmiAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAcercadeActionPerformed(evt);
            }
        });
        jmAyuda.add(jmiAcercade);

        jMenuBar1.add(jmAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlMensaje)
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jtfNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlMensaje)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saludarActionPerformed
        // TODO add your handling code here:
        jlMensaje.setText("Hola " + jtfNombre.getText() + " Bienvenido a mi aplicación con Swing");
        jlMensaje.setVisible(true);
    }//GEN-LAST:event_saludarActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void guardaTexto(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_guardaTexto
        // TODO add your handling code here:
        
        // jlMensaje.v
    }//GEN-LAST:event_guardaTexto

    private void jmiInicializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInicializarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiInicializarActionPerformed

    private void jmiAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAcercadeActionPerformed
        // TODO add your handling code here:
        String mensaje = "Aplicación con java Swing \n Autor: Ismael Barea Insua\n (c) 2021";
        String titulo = "Información de la aplicación";
        JOptionPane.showMessageDialog(rootPane, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmiAcercadeActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfAppSwingII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfAppSwingII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfAppSwingII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfAppSwingII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfAppSwingII().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlMensaje;
    private javax.swing.JMenu jmAcciones;
    private javax.swing.JMenu jmAyuda;
    private javax.swing.JMenuItem jmiAcercade;
    private javax.swing.JMenuItem jmiInicializar;
    private javax.swing.JMenuItem jmiSaludar;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
    
    private void inicializar(){
        jlMensaje.setVisible(false);
        jtfNombre.setText("");
    }
}
